# Generated by Django 6.0.7 on 2026-07-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Sent', max_length=10),
        ),
        migrations.AlterModelTable(
            name='emaillog',
            table='email_logs',
        ),
    ]
