# Generated by Django 6.0.7 on 2026-08-14 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_emaillog_options_alter_emaillog_recipient_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSendTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('total_emails', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Running', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_send_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Send Task',
                'verbose_name_plural': 'Bulk Send Tasks',
                'db_table': 'bulk_send_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
