# Generated by Django 6.0.7 on 2026-08-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_bulksendtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkSendTask',
        ),
    ]
