# Generated by Django 6.0.7 on 2026-09-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_bulksendtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_template',
            field=models.CharField(blank=True, default='standard', max_length=100),
        ),
    ]

