# Generated by Django 6.0.7 on 2026-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_emaillog_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
